spring.application.name=SpringRest_exceptions
spring.datasource.url=jdbc:mysql://localhost:3306/student_db_exceptions?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Pikachu@22
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true