spring.application.name=SpringRest15_ConstructionSite
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/inspection14db
spring.datasource.username=root
spring.datasource.password=Pikachu@22
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# File size limit
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB